package de.jplag.text.semantic;

import java.io.File;
import java.io.FileNotFoundException;
import java.nio.file.Path;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;

import de.jplag.reporting.reportobject.ReportObjectFactory;
import de.jplag.reporting.reportobject.model.ComparisonReport;
import de.jplag.reporting.reportobject.model.RunInformation;
import de.jplag.reporting.reportobject.model.SubmissionFile;
import de.jplag.reporting.reportobject.model.SubmissionFileIndex;
import de.jplag.reporting.reportobject.model.SubmissionMappings;
import de.jplag.reporting.reportobject.model.TopComparison;
import de.jplag.reporting.reportobject.writer.ZipWriter;

/**
 * Writes the engine's results as a {@code .jplag} report archive that opens in the standard JPlag report viewer.
 * <p>
 * It reuses JPlag's own {@link ZipWriter} and report DTO records so the format stays compatible with the viewer. The
 * engine's cosine score is mapped into the {@code AVG} (and {@code MAX}) similarity metric, which the viewer displays
 * and sorts by default. Since the engine produces document-level similarities rather than token matches, each
 * comparison is written with an empty {@code matches} list — the viewer shows the ranked pairs and their scores, but no
 * in-text highlighting.
 */
public class JPlagReportWriter {

    private static final String AVG = "AVG";
    private static final String MAX = "MAX";
    private static final String LONGEST_MATCH = "LONGEST_MATCH";
    private static final String MAXIMUM_LENGTH = "MAXIMUM_LENGTH";
    private static final int DISTRIBUTION_BUCKETS = 100;
    private static final String README = "This is a plagiarism report generated by the JPlag semantic text engine.%n"
            + "Similarities are TF-IDF cosine scores over WordNet-normalized terms (order-independent), stored in the AVG metric.";

    /**
     * Writes a viewer-compatible report.
     * @param submissions all analyzed submissions (used for display names and the file index).
     * @param results the reported pair similarities.
     * @param reportFile the target {@code .jplag} file.
     * @throws FileNotFoundException if the target file cannot be opened for writing.
     */
    public void write(List<AnalyzedSubmission> submissions, List<SubmissionPairSimilarity> results, File reportFile) throws FileNotFoundException {
        int submissionCount = submissions.size();
        int totalComparisons = submissionCount * (submissionCount - 1) / 2;
        ZipWriter writer = new ZipWriter(reportFile);
        try {
            writer.addJsonEntry(runInformation(totalComparisons), Path.of("runInformation.json"));
            writer.addJsonEntry(options(), Path.of("options.json"));
            writer.addJsonEntry(List.of(), Path.of("cluster.json"));
            writer.addJsonEntry(distribution(results), Path.of("distribution.json"));
            writer.addJsonEntry(topComparisons(results), Path.of("topComparisons.json"));
            writer.addJsonEntry(submissionMappings(submissions, results), Path.of("submissionMappings.json"));
            writer.addJsonEntry(submissionFileIndex(submissions), Path.of("submissionFileIndex.json"));
            for (SubmissionPairSimilarity result : results) {
                writer.addJsonEntry(comparisonReport(result), Path.of("comparisons", comparisonFileName(result)));
            }
            writer.writeStringEntry(String.format(README), Path.of("README.txt"));
        } finally {
            writer.close();
        }
    }

    private RunInformation runInformation(int totalComparisons) {
        String date = new SimpleDateFormat("dd/MM/yy", Locale.ROOT).format(new Date());
        return new RunInformation(ReportObjectFactory.REPORT_VIEWER_VERSION, List.of(), date, 0L, totalComparisons);
    }

    private Map<String, Object> options() {
        Map<String, Object> clustering = new LinkedHashMap<>();
        clustering.put("enabled", false);
        Map<String, Object> options = new LinkedHashMap<>();
        options.put("language", "text");
        options.put("similarityMetric", AVG);
        options.put("minimumTokenMatch", 0);
        options.put("clusteringOptions", clustering);
        options.put("normalize", false);
        return options;
    }

    private Map<String, Double> similarities(double score) {
        Map<String, Double> similarities = new LinkedHashMap<>();
        similarities.put(AVG, score);
        similarities.put(MAX, score);
        similarities.put(MAXIMUM_LENGTH, 0.0);
        similarities.put(LONGEST_MATCH, 0.0);
        return similarities;
    }

    private List<TopComparison> topComparisons(List<SubmissionPairSimilarity> results) {
        return results.stream()
                .map(result -> new TopComparison(result.firstSubmission(), result.secondSubmission(), similarities(result.similarity()))).toList();
    }

    private ComparisonReport comparisonReport(SubmissionPairSimilarity result) {
        return new ComparisonReport(result.firstSubmission(), result.secondSubmission(), similarities(result.similarity()), List.of(),
                result.similarity(), result.similarity());
    }

    private SubmissionMappings submissionMappings(List<AnalyzedSubmission> submissions, List<SubmissionPairSimilarity> results) {
        Map<String, String> submissionIds = new LinkedHashMap<>();
        submissions.forEach(submission -> submissionIds.put(submission.name(), submission.name()));

        Map<String, Map<String, String>> comparisonFiles = new LinkedHashMap<>();
        for (SubmissionPairSimilarity result : results) {
            String fileName = comparisonFileName(result);
            comparisonFiles.computeIfAbsent(result.firstSubmission(), key -> new LinkedHashMap<>()).put(result.secondSubmission(), fileName);
            comparisonFiles.computeIfAbsent(result.secondSubmission(), key -> new LinkedHashMap<>()).put(result.firstSubmission(), fileName);
        }
        return new SubmissionMappings(submissionIds, comparisonFiles);
    }

    private SubmissionFileIndex submissionFileIndex(List<AnalyzedSubmission> submissions) {
        Map<String, Map<String, SubmissionFile>> fileIndexes = new LinkedHashMap<>();
        for (AnalyzedSubmission submission : submissions) {
            Map<String, SubmissionFile> files = new LinkedHashMap<>();
            files.put(submission.name() + ".txt", new SubmissionFile(submission.length()));
            fileIndexes.put(submission.name(), files);
        }
        return new SubmissionFileIndex(fileIndexes);
    }

    private Map<String, int[]> distribution(List<SubmissionPairSimilarity> results) {
        int[] histogram = new int[DISTRIBUTION_BUCKETS];
        for (SubmissionPairSimilarity result : results) {
            int bucket = Math.min(DISTRIBUTION_BUCKETS - 1, Math.max(0, (int) (result.similarity() * DISTRIBUTION_BUCKETS)));
            histogram[bucket]++;
        }
        Map<String, int[]> distribution = new LinkedHashMap<>();
        distribution.put(AVG, histogram);
        distribution.put(MAX, histogram.clone());
        return distribution;
    }

    private String comparisonFileName(SubmissionPairSimilarity result) {
        return sanitize(result.firstSubmission()) + "-" + sanitize(result.secondSubmission()) + ".json";
    }

    private static String sanitize(String name) {
        return name.replaceAll("[^a-zA-Z0-9-_]", "_");
    }
}
